all: num1 num2 num3 num4 num5 num6 test

num1: num1.cpp
	clang++ -o num1 num1.cpp

num2: num2.cpp
	clang++ -o num2 num2.cpp

num3: num3.cpp
	clang++ -o num3 num3.cpp

num4: num4.cpp
	clang++ -o num4 num4.cpp

num5: num5.cpp
	clang++ -o num5 num5.cpp

num6: num6.cpp
	clang++ -o num6 num6.cpp

test: test.cpp
	clang++ -o test test.cpp
