all: num1 num2 num3 num4 num5

num1: num1.cpp
	clang++ -o num1 num1.cpp

num2: num2.cpp
	clang++ -o num2 num2.cpp

num3: num3.cpp
	clang++ -o num3 num3.cpp

num4: num4.cpp
	clang++ -o num4 num4.cpp

num5: num5.cpp
	clang++ -o num5 num5.cpp
