all: num1 num2 num3 num4 num5 num6 num7 num8 num9 num10 num11 num12 num13 num14 num15 num16 test2 test

num1: num1.cpp
	clang++ -o num1 num1.cpp

num2: num2.cpp
	clang++ -o num2 num2.cpp

num3: num3.cpp
	clang++ -o num3 num3.cpp

num4: num4.cpp
	clang++ -o num4 num4.cpp

num5: num5.cpp
	clang++ -o num5 num5.cpp

num6: num6.cpp
	clang++ -o num6 num6.cpp

num7: num7.cpp
	clang++ -o num7 num7.cpp

num8: num8.cpp
	clang++ -o num8 num8.cpp

num9: num9.cpp
	clang++ -o num9 num9.cpp

num10: num10.cpp
	clang++ -o num10 num10.cpp

num11: num11.cpp
	clang++ -o num11 num11.cpp

num12: num12.cpp
	clang++ -o num12 num12.cpp

num13: num13.cpp
	clang++ -o num13 num13.cpp

num14: num14.cpp
	clang++ -o num14 num14.cpp

num15: num15.cpp
	clang++ -o num15 num15.cpp

num16: num16.cpp
	clang++ -o num16 num16.cpp

num17: num17.cpp
	clang++ -o num17 num17.cpp

test: test.cpp
	clang++ -o test test.cpp

test2: test2.cpp
	clang++ -o test2 test2.cpp
